"""add document file size

Revision ID: d4186c2c9f7f
Revises: d49179ff6cb5
Create Date: 2026-07-22 23:03:55.239234
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d4186c2c9f7f"
down_revision: str | None = "d49179ff6cb5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("file_size", sa.Integer(), server_default="0", nullable=False)
    )
    op.alter_column("documents", "file_size", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "file_size")
    # ### end Alembic commands ###
